version: "3"
services:
  be-wahyu:
    build: ./
    ports:
      - "3000:3000"
  be-adjie:
    build: ../laundry-api
    ports:
      - "3001:3001"
  fe:
    build: ../laundry-fe
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
