apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-adjie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-adjie
  template:
    metadata:
      labels:
        app: be-adjie
    spec:
      containers:
        - name: be-adjie
          image: be-adjie-image
          ports:
            - containerPort: 3001
          env:
            - name: SUPABASE_URL
              value: "https://mrqxfpnvawbiyhpdrbju.supabase.co"
            - name: SUPABASE_KEY
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycXhmcG52YXdiaXlocGRyYmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5MDM1NjAsImV4cCI6MjA0NzQ3OTU2MH0.ZzJ0SZkDi7gZoaVQek4h3Nl4YLm16N9cpaq7CSAvRqE"
---
apiVersion: v1
kind: Service
metadata:
  name: be-adjie
spec:
  selector:
    app: be-adjie
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
